version: "3.9"

services:
  # ==========================
  # API GATEWAY
  # ==========================
  api-gateway:
    build: ./services/api-gateway
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
    depends_on:
      - user-service
      - product-service
      - order-service
      - payment-service

  # ==========================
  # MICROSERVICES
  # ==========================
  user-service:
    build: ./services/user-service
    ports:
      - "4001:4001"

  product-service:
    build: ./services/product-service
    ports:
      - "4002:4002"

  order-service:
    build: ./services/order-service
    ports:
      - "4003:4003"

  payment-service:
    build: ./services/payment-service
    ports:
      - "4004:4004"
